class RequestKeys {
  RequestKeys._();

  static const String role = 'role';
  static const String partnerRole = 'partner';
  static const String countryCode = 'country_code';
  static const String mobile = 'mobile';
  static const String phone = 'phone';
  static const String otp = 'otp';
  static const String name = 'name';
  static const String email = 'email';
  static const String photo = 'photo';
  static const String file = 'file';
  static const String folder = 'folder';
  static const String profileFolder = 'profile';
  static const String identityFolder = 'identity';
  static const String addressFolder = 'address';
  static const String bankFolder = 'bank';
  static const String docType = 'doc_type';
  static const String docNumber = 'doc_number';
  static const String frontUrl = 'front_url';
  static const String backUrl = 'back_url';
  static const String docUrl = 'doc_url';
  static const String addressLine = 'address_line';
  static const String landmark = 'landmark';
  static const String city = 'city';
  static const String state = 'state';
  static const String pincode = 'pincode';
  static const String sameAsDocument = 'same_as_document';
  static const String clientId = 'client_id';
  static const String redirectUrl = 'redirect_url';
  static const String holderName = 'account_holder_name';
  static const String accountNumber = 'account_number';
  static const String ifsc = 'ifsc';
  static const String bankName = 'bank_name';
  static const String bankBranch = 'bank_branch';
  static const String chequeUrl = 'cheque_url';
  static const String fcmToken = 'fcm-token';
  static const String deviceType = 'device_type';
  static const String deviceId = 'device_id';
  static const String status = 'status';
  static const String tab = 'tab';
  static const String page = 'page';
  static const String limit = 'limit';
}
