class AppAssets {
  AppAssets._();

  // --- WebP images (brand / screens) ---
  static const String logo = 'assets/images/webp/ap_logo_img.webp';
  static const String bgSplash = 'assets/images/webp/bg_splash_img.webp';
  static const String bg = 'assets/images/webp/bg_img.webp';
  static const String homeSideCar = 'assets/images/webp/home_side_car_img.webp';
  static const String otpIllustration = 'assets/images/webp/otp_img.webp';
  static const String dummyProfile = 'assets/images/webp/dummy_profile_img.webp';
  static const String dummyCar = 'assets/images/webp/dummy_car_img.webp';
  static const String bell = 'assets/images/webp/bell_img.webp';
  static const String logoutImage = 'assets/images/webp/logout_img.webp';
  static const String deleteAccountImage = 'assets/images/webp/delete_ac_img.webp';
  static const String success = 'assets/images/webp/success_img.webp';
  static const String reminder = 'assets/images/webp/reminder_img.webp';
  static const String map = 'assets/images/webp/map_img.webp';
  static const String carCity = 'assets/images/webp/car_city_img.webp';
  static const String city = 'assets/images/webp/city_img.webp';
  static const String carWash = 'assets/images/webp/car_wash_img.webp';
  static const String handShake = 'assets/images/webp/hand_img.webp';
  static const String headphone = 'assets/images/webp/ic_headphone_img.png';
  static const String imageUpload = 'assets/images/webp/image_upload_img.webp';

  // --- SVG chrome icons (replace with brand SVG/PNG when ready) ---
  static const String logoCar = 'assets/images/icons/ic_car.svg';
  static const String flagIn = 'assets/images/icons/ic_flag_in.svg';
  static const String back = 'assets/images/icons/ic_back.svg';
  static const String chevronRight = 'assets/images/icons/ic_chevron_right.svg';
  static const String chevronDown = 'assets/images/icons/ic_chevron_down.svg';
  static const String search = 'assets/images/icons/ic_search.svg';
  static const String notification = 'assets/images/icons/ic_notification.svg';
  static const String notificationFilled =
      'assets/images/icons/ic_notification_filled.svg';
  static const String home = 'assets/images/icons/ic_home.svg';
  static const String homeFilled = 'assets/images/icons/ic_home_filled.svg';
  static const String calendar = 'assets/images/icons/ic_calendar.svg';
  static const String calendarFilled = 'assets/images/icons/ic_calendar_filled.svg';
  static const String refer = 'assets/images/icons/ic_refer.svg';
  static const String rupee = 'assets/images/icons/ic_rupee.svg';
  static const String person = 'assets/images/icons/ic_person.svg';
  static const String personFilled = 'assets/images/icons/ic_person_filled.svg';
  static const String personId = 'assets/images/icons/ic_person_id.svg';
  static const String arrowForward = 'assets/images/icons/ic_arrow_forward.svg';
  static const String edit = 'assets/images/icons/ic_edit.svg';
  static const String camera = 'assets/images/icons/ic_camera.svg';
  static const String copy = 'assets/images/icons/ic_copy.svg';
  static const String share = 'assets/images/icons/ic_share.svg';
  static const String logout = 'assets/images/icons/ic_logout.svg';
  static const String delete = 'assets/images/icons/ic_delete.svg';
  static const String refresh = 'assets/images/icons/ic_refresh.svg';
  static const String send = 'assets/images/icons/ic_send.svg';
  static const String navigate = 'assets/images/icons/ic_navigate.svg';
  static const String help = 'assets/images/icons/ic_help.svg';
  static const String check = 'assets/images/icons/ic_check.svg';
  static const String checkCircle = 'assets/images/icons/ic_check_circle.svg';
  static const String progressCheck = 'assets/images/icons/ic_progress-check.svg';
  static const String progressDown = 'assets/images/icons/ic_progress-down.svg';
  static const String cancel = 'assets/images/icons/ic_cancel.svg';
  static const String circle = 'assets/images/icons/ic_circle.svg';
  static const String lock = 'assets/images/icons/ic_lock.svg';
  static const String lockFilled = 'assets/images/icons/ic_lock_filled.svg';
  static const String shield = 'assets/images/icons/ic_shield.svg';
  static const String clock = 'assets/images/icons/ic_clock.svg';
  static const String phone = 'assets/images/icons/ic_phone.svg';
  static const String phoneAndroid = 'assets/images/icons/ic_phone_android.svg';
  static const String email = 'assets/images/icons/ic_email.svg';
  static const String headset = 'assets/images/icons/ic_headset.svg';
  static const String location = 'assets/images/icons/ic_location.svg';
  static const String badge = 'assets/images/icons/ic_badge.svg';
  static const String aadhaar = 'assets/images/icons/ic_aadhaar.svg';
  static const String pan = 'assets/images/icons/ic_pan.svg';
  static const String drivingLicense = 'assets/images/icons/ic_driving_license.svg';
  static const String bank = 'assets/images/icons/ic_bank.svg';
  static const String folder = 'assets/images/icons/ic_folder.svg';
  static const String document = 'assets/images/icons/ic_document.svg';
  static const String privacy = 'assets/images/icons/ic_privacy.svg';
  static const String campaign = 'assets/images/icons/ic_campaign.svg';
  static const String assignment = 'assets/images/icons/ic_assignment.svg';
  static const String flash = 'assets/images/icons/ic_flash.svg';
  static const String flashFilled = 'assets/images/icons/ic_flash_filled.svg';
  static const String rocket = 'assets/images/icons/ic_rocket.svg';
  static const String verified = 'assets/images/icons/ic_verified.svg';
  static const String code = 'assets/images/icons/ic_code.svg';
  static const String star = 'assets/images/icons/ic_star.svg';
}
